baseURL = "https://elections.openeastleigh.uk"
languageCode = "en-gb"
title = "Eastleigh Elections"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "Open Eastleigh"
  url = "https://www.openeastleigh.uk/"
  description = "Everything you need to know about the Eastleigh Central ward candidates for the local by-election!"
  images = ['/images/logo.png']
  message = "Eastleigh local by-election, 8 May 2025"
  hideAutoMenu = false

[params.timetable]
  nominations = 2024-06-07T16:00:00Z
  register = 2024-06-18T23:59:00Z
  postal = 2024-06-19T17:00:00Z
  proxy = 2024-06-26T17:00:00Z
  photoid = 2024-06-26T17:00:00Z
