baseURL = "https://elections.openeastleigh.uk"
languageCode = "en-gb"
title = "Eastleigh Elections"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "Open Eastleigh"
  url = "https://www.openeastleigh.uk/"
  description = "Find all your candidates and hustings videos for the 2023 Eastleigh local elections!"
  images = ['/images/logo.png']
  message = "Eastleigh local election Thursday 4 May 2023"
  hideAutoMenu = false

[params.timetable]
  register = 2023-04-17T23:59:00
  postal = 2023-04-18T17:00:00
  proxy = 2023-04-25T17:00:00
  photoid = 2023-04-25T17:00:00

[social]
  twitter = "ESLHustings"
